# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlindBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlindBoard
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/Storage'
  pod 'SDWebImage'

end
